### ISSUE TITLE
Test fails with babel

### ISSUE THREAD

**Issue by yacut** [yacut/tester-jest#1]
Test fails with babel

```
● Test suite failed to run

    /src/some.spec.jsx:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
```

**Comment by yacut** [comment]
The reason: The spawn runner process set wrong cwd option.

**Comment by yacut** [comment]
The problem was in .babelrc config. I've changed it from:
```json
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ],
    "react",
    "stage-0"
  ],
  "plugins": [],
  "env": {
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs"
      ]
    }
  }
}
```

to:

```json
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "plugins": [],
  "env": {
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs"
      ]
    }
  }
}
```
Works fine.

**Comment by yacut** [comment]
If you need `"modules": false` in your .babelrc. Atom Dev Mode can solve this problem. :)

**Comment by yacut** [comment]
Since v0.1.11 you can set NODE_ENV in settings.

**Comment by thejamespower** [comment]
I'm struggling with this issue too. `.babelrc`:
```
{
  "plugins": ["lodash"],
  "presets": [
    ["es2015", { "modules": false }],
    "react",
    "stage-0"
  ],
  "env": {
    "test": {
      "presets": ["es2015"]
    }
  }
}
```

I have set `NODE_ENV` to `test` in tester-jest settings.

Jest runs fine via the CLI.
