### ISSUE TITLE
Doesnt seem to work...

### ISSUE THREAD

**Issue by mikeerickson** [yacut/tester-jest#14]
I am trying to get the simplest test working, but I always receive an error (see screenshot) . 

![image](https://user-images.githubusercontent.com/183153/29142432-c2e0a96e-7d06-11e7-866c-1e10e3dec93b.png)

simple test file (__tests__/sample.test.js)

```
test('sample', () => {
  let fname = 'Mike'
  expect(fname).toEqual('Mike')
});
```

I never see anything close to that in the gif image in readme

**Comment by bronson** [comment]
FWIW your testfile works just fine for me.

![screen shot 2017-09-02 at 5 37 04 pm](https://user-images.githubusercontent.com/1776/29999641-67df869a-9005-11e7-80fb-8d10071ed50b.png)

What platform are you running on?  What version of Jest?  (Mac, 20.0.04 for me)

**Comment by Boo-urns** [comment]
With that sample test above I'm receiving
```
 ● Test suite failed to run

    TypeError: Path must be a string. Received undefined
      
      at assertPath (path.js:7:11)
      at Object.relative (path.js:1226:5)
```

What step am I missing @bronson ?

**Comment by Boo-urns** [comment]
Looks like updating `jest` resolved the issue for me!

**Comment by yacut** [comment]
@Boo-urns the issue could related to https://github.com/facebook/jest/issues/3520
I will update dependencies soon.

**Comment by EdwardSalter** [comment]
I had this same issue until I realised that I had deleted my `node_modules` folder and not run an `npm install` again. :grimacing:
