### ISSUE TITLE
Fails to activate if package.json has no devDependencies

### ISSUE THREAD

**Issue by Tol1** [yacut/tester-jest#19]
I.E. create-react-app don't use package.json devDependencies, instead everything is on dependencies.
This package fails to activate in such cases, as it's trying to fetch package names from undefined object (`Object.keys(undefined)`)

1. Create react app with create-react-app
2. Eject
3. Try to activate

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tester-jest](https://github.com/yacut/tester-jest) package 1.2.0

### Stack Trace

Failed to activate the tester-jest package

```
At Cannot convert undefined or null to object

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /packages/tester-jest/lib/tester-jest.js:26:24
    at Array.map (native)
    at Object.activate (/packages/tester-jest/lib/tester-jest.js:26:6)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:255:25)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:695:42)
    at packagesToEnable.forEach.name (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:440:30)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:84:32)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

**Comment by yacut** [comment]
related to #24

**Comment by yacut** [comment]
Please try v1.2.4
