### ISSUE TITLE
Failed to activate the tester-jest package

### ISSUE THREAD

**Issue by debugger24** [yacut/tester-jest#21]
**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [tester-jest](https://github.com/yacut/tester-jest) package 1.2.0

### Stack Trace

Failed to activate the tester-jest package

```
At Cannot convert undefined or null to object

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /packages/tester-jest/lib/tester-jest.js:26:24
    at Array.map (native)
    at Object.activate (/packages/tester-jest/lib/tester-jest.js:26:6)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:841:27)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-clock 0.1.16 
atom-jest-snippets 2.0.0 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
code-links 0.4.0 
file-icons 2.1.16 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.13.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.6.10 
platformio-ide-terminal 2.8.0 
react 0.18.0 
react-snippets 1.0.1 
tester 1.4.0 
tester-jest 1.2.0 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```

**Comment by turlockmike** [comment]
Same issue

**Comment by yacut** [comment]
Please try v1.2.4
